---
- name: Check if pf9-ostackhost is installed (RedHat)
  shell: "`which rpm` -qa | grep pf9-ostackhost > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: ostackhost_installed
  when:
    - ansible_pkg_mgr == "yum"

- set_fact: ostackhost_pkg_state="{{ ostackhost_installed.stdout.strip() }}"
  when: ostackhost_installed.changed

- name: debug
  debug: var=ostackhost_pkg_state

- name: install required multipath yum packages
  shell: "yum install -y device-mapper-multipath sysfsutils sg3_utils"
