---
- name: Check if pf9-ostackhost is installed (Rocky)
  shell: "`which dnf` list installed | grep \"^pf9-ostackhost\\.\" > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: pkg_state_ostackhost_redhat
  when:
    - ansible_pkg_mgr == "dnf"

- name: install device-mapper-multipath
  dnf:
    name: device-mapper-multipath
    state: present

- name: install sysfsutils
  dnf:
    name: sysfsutils
    state: present

- name: install sg3_utils
  dnf:
    name: sg3_utils
    state: present
