#!/bin/bash

method_usage() {
  echo "get-provider"
  exit 1
}

# process paramters
if [ $# -eq 1 -a "${1}" == "-h" ]; then
  method_usage
fi

# invoke API
result=`curl -k -H "Content-Type: application/json" -H "X-Auth-Token: ${token}" ${du_url}/qbert/v1/cloudproviders 2>/dev/null`
if [ $? -ne 0 ]; then exit 1; fi
echo ${result} | grep ^404 > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo ${result}
  exit 1
fi
echo ${result} | python -m json.tool
echo -e "\nProviders : `echo ${result} | python -m json.tool | grep '"id": "' | wc -l`"
