#!/bin/bash
################################################################################
## Platform9 Openstack Assimilation Utility
## Copyright(c) 2018 Platform9 Systems, Inc.
################################################################################

# initialize variables
basedir=$(dirname $0)
min_ansible_version="2.2"
inventory=${basedir}/inventory/hosts
autodeplopy_script=${basedir}/pf9-autodeploy.yml
help_file=${basedir}/lib/help.txt
platform=""
target=""
target_type=""
log=${basedir}/lib/INSTALL.log
pf9_config=${basedir}/pf9-autodeploy.conf
pf9_config_tpl=${basedir}/lib/pf9-autodeploy.tpl
pf9_group_vars=${basedir}/group_vars/all.yml
pf9_custom_configFile=""
flag_setup=0
flag_prereqs=0
flag_autoregister=0

# functions
usage() {
  echo "Usage: $0 [Args] <target>"
  echo -e "\nArgs (Optional):\n"
  echo "-a|--autoRegister        : auto-register host with control plane"
  echo "-i|--installPrereqs      : install pre-requisites and exit"
  echo "-s|--setup               : run setup and exit"
  echo "-c|--config <configFile> : use custom configuration file"
  echo -e "-h|--help                : display this message\n"
  if [ $# -eq 1 -a "${1}" == "-q" ]; then
    :
  else
    exit 1
  fi
}

validate_platform() {
  # check if running CentOS 7.4
  if [ -r /etc/centos-release ]; then
    release=$(cat /etc/centos-release | cut -d ' ' -f 4)
    if [[ ! "${release}" == 7.4.* ]]; then assert "unsupported CentOS release: ${release}"; fi
    platform="centos"
    host_os_info=$(cat /etc/centos-release)
  elif [ -r /etc/lsb-release ]; then
    release=$(cat /etc/lsb-release | grep ^DISTRIB_RELEASE= /etc/lsb-release | cut -d '=' -f2)
    if [[ ! "${release}" == 16.04* ]]; then assert "unsupported CentOS release: ${release}"; fi
    platform="ubuntu"
    ubuntu_release=$(cat /etc/lsb-release | grep ^DISTRIB_RELEASE | cut -d = -f2)
    host_os_info="${platform} ${ubuntu_release}"
  else
    assert "unsupported platform"
  fi
}

banner() {
  echo "################################################################"
  echo "# Platform9 Auto-Deplopy Utility (Version 0.1)"
  echo "################################################################"
}

help() {
  if [ -r ${help_file} ]; then 
    usage -q
    cat ${help_file}
  else
    assert "help file missing"
  fi
  exit 0
}

install_prereqs() {
  # install Ansibl (and dependencies)
  echo -n "--> Validating package dependencies: "
  if [ "${platform}" == "centos" ]; then
    for pkg in epel-release nginx ansible gcc python-devel python2-pip bc; do
      echo -n "${pkg} "
      rpm -q ${pkg} > /dev/null 2>&1
      if [ $? -ne 0 ]; then
        sudo yum -y install ${pkg} > ${log} 2>&1
        if [ $? -ne 0 ]; then
          echo -e "\nERROR: failed to install ${pkg} - here's the log:\n"
          cat ${log}; exit 1
        fi
      fi
    done
  elif [ "${platform}" == "ubuntu" ]; then
    # add ansible repository
    dpkg-query -f '${binary:Package}\n' -W | grep ^${pkg}$ > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      sudo apt-add-repository -y ppa:ansible/ansible > /dev/null 2>&1
      sudo apt-get update> /dev/null 2>&1
      sudo apt-get -y install ansible > ${log} 2>&1
      if [ $? -ne 0 ]; then
        echo -e "\nERROR: failed to install ${pkg} - here's the log:\n"
        cat ${log}; exit 1
      fi
    fi

  for pkg in ansible bc ntp python-pip; do
      echo -n "${pkg} "
      dpkg-query -f '${binary:Package}\n' -W | grep ^${pkg}$ > /dev/null 2>&1
      if [ $? -ne 0 ]; then
        sudo apt -y install ${pkg} > ${log} 2>&1
        if [ $? -ne 0 ]; then
          echo -e "\nERROR: failed to install ${pkg} - here's the log:\n"
          cat ${log}; exit 1
        fi
      fi
    done
  fi

  ## upgrade pip
  sudo pip install --upgrade pip > ${log} 2>&1
  if [ $? -ne 0 ]; then
    echo -e "\nERROR: failed to upgrade pip - here's the log:\n"
    cat ${log}; exit 1
  fi

  ## install python shade
  echo -n "python-shade "
  sudo pip install shade > ${log} 2>&1
  if [ $? -ne 0 ]; then
    echo -e "\nERROR: failed to install python shade - here's the log:\n"
    cat ${log}; exit 1
  fi

  ## install setupd
  echo -n "setupd"
  sudo yum -y install ${basedir}/lib/setupd.rpm > ${log} 2>&1
  if [ ! -d /opt/pf9/setupd ]; then
    echo -e "\nERROR: failed to install setupd\n"
    cat ${log}; exit 1
  fi
  echo

  # create log directory
  if [ ! -d /var/log/pf9 ]; then mkdir -p /var/log/pf9; fi

  # update setupd packages
  echo -n "--> Updating setupd libraries: "
  for pkg in pf9_master_setup.py pf9_utils.py pf9_mgmt_setup.py; do
    echo -n "${pkg} "
    /bin/cp -f ${basedir}/scripts/setupd-updates/${pkg} /opt/pf9/setupd/lib/python2.7/site-packages/setupd_samples/utils/${pkg} > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo; assert "failed to update ${pkg}"
    fi
  done

  for pkg in attach-node add-cluster; do
    echo -n "${pkg} "
    /bin/cp -f ${basedir}/scripts/setupd-updates/${pkg} /opt/pf9/setupd/bin/${pkg} > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo; assert "failed to update ${pkg}"
    fi
  done
  echo
}

################################################################################
## main
################################################################################
# incliude libraries
source ${basedir}/lib/config_util.sh
source ${basedir}/lib/utility.sh

## validate commandline arguments
if [ $# -lt 1 ]; then usage; fi
while [ $# -gt 0 ]; do
  case ${1} in
  -h|--help)
    help ;;
  -s|--setup)
    if [ ! -r ${pf9_config} ]; then init_config; fi
    flag_setup=1
    ;;
  -i|--installPrereqs)
    flag_prereqs=1
    ;;
  -a|--autoRegister)
    flag_autoregister=1
    ;;
  -c|--config)
    if [ $# -lt 2 ]; then usage; fi
    pf9_custom_configFile=${2}
    shift
    ;;
  *)
    if [ $# -ne 1 ]; then usage; fi
    target=${1}
    ;;
  esac
  shift
done

# validate platform (CentOS 7.4 or Ubuntu 16.04)
validate_platform

## enforce setup/custom-config mutual exclusivity
if [ ${flag_setup} -eq 1 -a -n "${pf9_custom_configFile}" ]; then assert "'-s' and '-c' are mutually exclusive"; fi

## run setup
if [ ${flag_setup} -eq 1 ]; then
  run_setup
  exit 0
fi

## install prequisite packages
if [ ${flag_prereqs} -eq 1 ]; then
  install_prereqs; echo
  exit 0
fi

## use custom config (if specified on commandline)
if [ -n "${pf9_custom_configFile}" ]; then pf9_config=${pf9_custom_configFile}; fi

## build group_vars/all.yml
build_config

## validate target
if [ -z "${target}" ]; then usage; fi

## validate sudo priviledges
sudo bash <<< "exit 200"
if [ $? -ne 200 ]; then assert "you need sudo privilidges to run this script - please update /etc/sudoers"; fi

## search for target in Ansible inventory
grep ^${target} ${inventory} > /dev/null 2>&1
if [ $? -eq 0 ]; then
  target_type="host"
else
  grep "^\[${target}\]" ${inventory} > /dev/null 2>&1
  if [ $? -eq 0 ]; then target_type="group"; fi
fi

## validate target found
case ${target_type} in
host|group)
  ;;
*)
  assert "target not found in Ansible inventory"
  ;;
esac

## display banner
banner

# run setup if config file missing
if [ ! -r ${pf9_config} ]; then
  init_config
  run_setup
fi

# validate all config values are set
validate_config

# install prerequisite packages
install_prereqs

## validate minimum Ansible version
ansible_version=$(ansible --version | head -1 | cut -d ' ' -f2 | cut -d . -f1-2)
echo "--> ansible_version = ${ansible_version}"
if (( ! $(bc <<< "$ansible_version >= $min_ansible_version") )); then assert "Ansible ${min_ansible_version} or greater is required"; fi

## lookup configuration values from config file
du_username=$(grep ^os_username ${pf9_config} | cut -d \| -f2)
du_password=$(grep ^os_password ${pf9_config} | cut -d \| -f2)
nova_dns_domain=$(grep ^nova_dns_domain ${pf9_config} | cut -d \| -f2)

## assign/validate ctrl_ip from config file and resolve IP for ctrl_hostname
ctrl_hostname=$(grep ^du_url ${pf9_config} | cut -d \| -f2 | cut -d \/ -f3)
tmp_ip=$(ping -c 1 ${ctrl_hostname} | grep PING | cut -d ' ' -f3)
ctrl_ip=${tmp_ip:1:((${#tmp_ip}-2))}

## toggle auto-regsister flag
if [ ${flag_autoregister} -eq 1 ]; then
  autoreg="on"
else
  autoreg="off"
fi

## inform user of Ansible command being run
echo -e "\n[Executing: ansible-playbook ${autodeplopy_script}]"

## call pf9-autopdeplopy
ansible-playbook -i ${inventory} -l ${target} -e "autoreg=${autoreg} nova_dns_domain=${nova_dns_domain} ctrl_ip=${ctrl_ip} du_username=${du_username} du_password=${du_password}" ${autodeplopy_script}

## exit cleanly
exit 0
