---
- name: Check if pf9-ceilometer in installed (Ubuntu)
  shell: "`which dpkg-query` -s pf9-ceilometer > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: ceilometer_installed
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_pkg_mgr == "apt"

- set_fact: ceilometer_pkg_state="{{ ceilometer_installed.stdout.strip() }}"
  when: ceilometer_installed.changed

- name: Check if pf9-ceilometer is installed (RedHat)
  shell: "`which rpm` -qa | grep pf9-ceilometer > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: ceilometer_installed
  when:
    - ansible_os_family == "RedHat"
    - ansible_pkg_mgr == "yum"

- set_fact: ceilometer_pkg_state="{{ ceilometer_installed.stdout.strip() }}"
  when: ceilometer_installed.changed

- name: Check if pf9-ceilometer is installed (Rocky)
  shell: "`which dnf` list installed | grep \"^pf9-ceilometer\\.\" > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: ceilometer_installed
  when:
    - ansible_distribution == "Rocky"
    - ansible_pkg_mgr == "dnf"

- set_fact: ceilometer_pkg_state="{{ ceilometer_installed.stdout.strip() }}"
  when: ceilometer_installed.changed

- name: debug
  debug: var=ceilometer_pkg_state

- name: Configure Ceilometer pipeline.yaml
  template:
    src: pipeline.yaml.j2
    dest: /opt/pf9/etc/ceilometer/pipeline.yaml
  when: ceilometer_pkg_state is defined and ceilometer_pkg_state != "not-installed"
  notify: restart pf9-ceilometer
