---
- name: Check if pf9-ostackhost in installed (Ubuntu)
  shell: "`which dpkg-query` -s pf9-ostackhost > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: ostackhost_installed
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_pkg_mgr == "apt"

- set_fact: ostackhost_pkg_state="{{ ostackhost_installed.stdout.strip() }}"
  when: ostackhost_installed.changed

- name: Check if pf9-ostackhost is installed (RedHat)
  shell: "`which rpm` -qa | grep pf9-ostackhost > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: ostackhost_installed
  when:
    - ansible_os_family == "RedHat"
    - ansible_pkg_mgr == "yum"

- name: debug
  debug: var=ansible_os_family

- set_fact: ostackhost_pkg_state="{{ ostackhost_installed.stdout.strip() }}"
  when: ostackhost_installed.changed

- name: Check if pf9-ostackhost is installed (Rocky)
  shell: "`which dnf` list installed | grep \"^pf9-ostackhost\\.\" > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: ostackhost_installed
  when:
    - ansible_distribution == "Rocky"
    - ansible_pkg_mgr == "dnf"

- set_fact: ostackhost_pkg_state="{{ ostackhost_installed.stdout.strip() }}"
  when: ostackhost_installed.changed

- name: debug
  debug: var=ostackhost_pkg_state

- name: update Nova to support nested virtualization
  script: files/update-nova.sh
  when: ostackhost_pkg_state is defined and ostackhost_pkg_state != "not-installed"
