---
- name: Add execute permission to installer
  file:
    path: "/tmp/platform9-install-{{ansible_os_family|lower}}.sh"
    mode: 0755

# install pf9-hostagent with a proxy
# NOTE: This installer cannot work with multiple regions today
- name: Install pf9-hostagent on hypervisor/containervisor (RedHat)
  shell: "/tmp/platform9-install-{{ansible_os_family|lower}}.sh --controller={{du_fqdn}} --project-name={{os_tenant}} --username={{os_username}} --password='{{os_password}}' --proxy={{proxy_url}} --no-ntpd --skip-os-check"
  register: agent_install
  when: proxy_url is defined

# install pf9-hostagent without a proxy
- name: Install pf9-hostagent on hypervisor/containervisor (RedHat)
  shell: "/tmp/platform9-install-{{ansible_os_family|lower}}.sh --controller={{du_fqdn}} --project-name={{os_tenant}} --username={{os_username}} --password='{{os_password}}' --no-proxy --no-ntpd --skip-os-check"
  when: proxy_url is undefined

