---
- name: Add execute permission to installer
  file:
    path: "/tmp/platform9-install-{{os_region}}-{{ansible_os_family|lower}}.sh"
    mode: 0755

# install pf9-hostagent with a proxy
- name: Install pf9-hostagent on hypervisor/containervisor
  shell: "/tmp/platform9-install-{{os_region}}-{{ansible_os_family|lower}}.sh --proxy={{proxy_url}} --no-ntpd --skip-os-check"
  register: agent_install
  when: proxy_url is defined

# install pf9-hostagent without a proxy
- name: Install pf9-hostagent on hypervisor/containervisor
  shell: "/tmp/platform9-install-{{os_region}}-{{ansible_os_family|lower}}.sh --no-proxy --no-ntpd --skip-os-check"
  when: proxy_url is undefined
