---
- name: Check pf9-hostagent is installed (Rocky)
  shell: "`which dnf` list installed | grep \"^pf9-hostagent\\.\" > /dev/null 2>&1; if [ $? -ne 0 ]; then echo 'not-installed'; fi"
  register: hostagent_installed
  when:
    - ansible_distribution == "Rocky"
    - ansible_pkg_mgr == "dnf"

- set_fact: hostagent_pkg_state="{{ hostagent_installed.stdout.strip() }}"
  when: hostagent_installed.changed

- set_fact:
    agent_platform: "redhat"
