---
# CentOS
- block:
  - name: install the latest version ca-certificates
    yum:
      name: ca-certificates
      state: latest
  when: ansible_distribution == "CentOS"

- name: Create Glance image library path
  file:
    path: "{{glance_filesystem_store_datadir}}"
    state: directory
    recurse: yes
    owner: pf9
    group: pf9group
  tags: 
    - image-import

- include: os-image-download.yml
