---
- block:
  - name: Enable and start Kernel Same-Page Merging (RedHat)
    service:
      name: ksm
      state: restarted
      enabled: yes

  - name: Enable and start Kernel Same-Page Merging Tuning
    service:
      name: ksmtuned
      state: restarted
      enabled: yes
  when: '"RedHat" in ansible_distribution or ansible_distribution == "CentOS" or ansible_distribution == "Rocky"'

- block:
  - name: Install Kernel Same-Page Merging (Ubuntu)
    apt:
      name: ksmtuned
      state: latest

  - name: Enable and start Kernel Same-Page Merging Tuning
    service:
      name: ksmtuned
      state: restarted
      enabled: yes
  when: ansible_distribution == "Ubuntu"
