---
libvirt_pki_path: /etc/pf9/certs/libvirt
sshd_service_name: "{% if 'RedHat' in ansible_distribution or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' %}sshd{% elif ansible_distribution == 'Ubuntu' %}ssh{% endif %}"
libvirtd_service_name: "{% if ansible_distribution_version == '18.04' %}libvirt-bin{% else %}libvirtd{% endif %}"
