---
- name: Install required yum common packages
  shell: "yum install -y libselinux-python libselinux-python3 ca-certificates"

- name: Modify devpts mount point
  mount:
    state: present
    name: /dev/pts
    src: devpts
    fstype: devpts
    opts: gid=5,mode=620
    dump: 0
    passno: 0
  register: devpts_result

- name: Remount devpts mount point
  command: mount -o remount devpts
  when: devpts_result is changed
