---
- name: Install libselinux-python
  dnf:
    state: present
    name: python3-libselinux

- name: Install the latest version ca-certificates
  dnf:
    name: ca-certificates
    state: latest

- name: Modify devpts mount point
  mount:
    state: present
    name: /dev/pts
    src: devpts
    fstype: devpts
    opts: gid=5,mode=620
    dump: 0
    passno: 0
  register: devpts_result

- name: Remount devpts mount point
  command: mount -o remount devpts
  when: devpts_result is changed
