#!/usr/bin/env python
# Copyright (c) 2018 Platform9 Systems

# A script that reads the required configuration files and
# prepares the host by downloading and caching the images


import argparse, sys, logging, yaml
from setupd_samples.utils.docker_save_load import import_all_images, pull_images, save_all_images
LOG = logging.getLogger(__name__)



def _setup_logs():
    root = logging.getLogger()
    root.setLevel(logging.DEBUG)

    ch = logging.FileHandler('/var/log/pf9-prepare-host.log')
    ch.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s - %(message)s')
    ch.setFormatter(formatter)
    root.addHandler(ch)


def _parse_args():
    ap = argparse.ArgumentParser(sys.argv[0],
	    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument('--image-dir', required=True, dest='image_dir',
	    help='Directory where all the images are stored')
    return ap.parse_args()


def _default_install(image_dir):

    print "Populating Docker cache"
    import_all_images(image_dir)


def main():
    args = _parse_args()
    _setup_logs()
    _default_install(args.image_dir)


if __name__ == '__main__':
    try:
        main()
        print "Done"
    except Exception as ex:
        print "Operation failed"
        LOG.exception(ex)
        LOG.critical('Really bad things happened: %s', str(ex))
        sys.exit(1)

