[all]
[all:vars]
#ansible_ssh_pass=Pl@tform9
#ansible_sudo_pass=Pl@tform9
ansible_ssh_private_key_file=~/cm-master
manage_network=True
live_migration=True
nested_virt=True
kernel_same_page_merging=False
