---
# CentOS
- block:
  - name: ensure contentdir is configured in yum vars
    copy:
      dest: /etc/yum/vars/contentdir
      content: 'centos'

  - name: install the centos-release-qemu-ev repo
    yum:
      name: centos-release-qemu-ev
      state: latest

  - name: install the latest version of qemu-kvm-ev
    yum:
      name: qemu-kvm-ev
      state: latest
  when: ansible_distribution == "CentOS"

# RedHat
- block:
  - name: install qemu packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - qemu-kvm
      - qemu-kvm-common
      - qemu-kvm-tools
      - qemu-guest-agent
      - libvirt-daemon-driver-qemu
  when: ansible_distribution == "RedHat"
